// import { Jarra } from "./Jarra";
// import { JarraLimitada } from "./Jarra";

// let jarra1:Jarra = new Jarra(10, 4);
// let jarra2:Jarra = new Jarra(15, 8);
// console.log("Jarras");
// console.log(jarra1);
// console.log(jarra2);
// console.log("ToString de Jarra 2");
// console.log(jarra2.toString());
// console.log("Aplicado el metodo llenardesde");
// jarra1.llenarDesde(jarra2);
// console.log(jarra1);
// console.log(jarra2);
// console.log("Comparacion de jarras");
// console.log(Jarra.comparar(jarra1, jarra2));
// console.log("Jarras de la clase JarrasLimitadas");
// let jarra3:JarraLimitada = new JarraLimitada(10, 4);
// console.log(jarra3);
// console.log("Aplicamos a la jarra 3 el metodo vaciarMitad");
// jarra3.vaciarMitad();
// console.log(jarra3);
// console.log("Jarra 4 con capacidad mayor a 10");
// let jarra4 = new JarraLimitada(11, 8);